### ISSUE TITLE
Mer nyanserad bild av utsläppsminskningar per år på kartan

### ISSUE THREAD

**Issue by carwei** [Klimatbyran/klimatkollen#195]
I färgskalan på Sverige-kartan finns det en kategori som är 3-10%. Mitt förslag är att bryta upp denna i minst 2 eller rent av 3 kategorier. Tänker så här:
- Med reservation för att jag är färgblind så verkar en hel del vara gult idag.
- Det är en enorm skillnad på att i genomsnitt ligga på 3-4 % minskningar per år eller 9-10 % per år.

I samband med detta borde dock färgvalen ses över. Tänker så här:
- Färgvalet borde spegla koldioxidbudgeten som ligger i botten för Klimatkollens budskap.
- Utgångspunkten på övriga delar av sidan är ju (mycket riktigt) är att visualisera 1,5-gradersmålet
- Färgskalan bör därför spegla en exponentiell minskning per år på 21-38 % alternativt en linjär minskning (snabbt räknat) på 15-20 %-enheter per år. 
- Misstänker att nuvarande data inte är procentenheter, men osäker. Forskarna rekomenderar väl dock oavsett en exponentiell utsläppsminskning framför linjärt (min tolkning eftersom den förtydligar hur viktigt det faktiskt är/var med minskningar redan 2022 under avsnittet "6. Be warned of the consequences of delay"). 
- Man kan då tänka sig att 15-20 % är grönt
- 10-15 %, som ni idag har som "ljusgrön" tycker jag är gränsfall eftersom det inte finns någon annan referenspunkt på kartan och 11% egentligen är tydligt underkant jämfört mot vad koldioxidbudgeten säger behöver göras.
- Men kan man kalla någonting mindre än 10 % för gult? När borde det börja bli orange? Strikt tolkat utifrån vad koldioxidbudgeten.

Hoppas att ni förstår hur jag försöker utmana er. Det vore rimligt att i praktiken addera (minst) en till färg som är mera röd och "bumpa upp" färgläggningen på kartan i samband med att man bryter upp kategorin 3-10%.

![bild](https://user-images.githubusercontent.com/31320065/229497627-959c2c19-ff49-4b01-a921-63f0ee4e8cb1.png)

**Comment by elvbom** [comment]
Tack för input och håller helt med. Du har helt rätt i att kartan domineras av gult och att det är bra stor skillnad på utsläppsminskningar med 3 eller 10%/år. Vi håller på att ta fram en ny färgskala från sidan, och att ha fler färger i "temperaturskalan" kommer vara en del av det, så värdefullt att höra att även du reagerar på det

**Comment by LudwikJaniuk** [comment]
Is this still an issue? @elvbom @carwei

**Comment by carwei** [comment]
Färgskalan verkar justerats men mer kontrastmässigt än att den bättre skulle spegla innebörden. 

Se uppdaterad skärmbild från idag. Jag tycker fortfarande att det är för positiv färgläggning. De tre första kategorierna (0, 0-1 och 1-2) borde alla vara röda (kanske rent av slås ihop?). Intrycket av kartan är att det bara är några enstak röda. Men allt under 5% är ju helt undermåligt i relation till vad budgetarna kräver, borde därför vara rött. Spontant 6-10 % som kanske kunde vara gult (i bemärkelsen att det fortfarande är en skarp varning).

Är det verkligen meningsfullt att skilja på 0-1 och 1-2 % minskning? Det är ju nästan avrundningsfel i det här sammanhanget.

![IMG_5846](https://github.com/Klimatbyran/klimatkollen/assets/31320065/9fa5dedd-7838-463c-bf4f-6598321b5f6f)

**Comment by carwei** [comment]
> Generellt tänker jag att vi kan (och ska) göra ett bättre jobb i att guida användare gällande kring vad som är OK och inte gällande datan, i dagsläget är det för otydligt.

@elvbom Det är ett fantastiskt verktyg, men jag tänker att man bara får ut maximal effekt om man förmedlar tydligare vad som egentligen är tillräckligt. Det är lätt att tappa bort just nu och t.ex. fastna i en relativ jämförelse mellan kommuner.

**Comment by elvbom** [comment]
Blocked by #432

**Comment by carwei** [comment]
Stort tack för att ni tog vara på min feedback. Ser betydligt mer rättvisande ut:

![image](https://github.com/Klimatbyran/klimatkollen/assets/31320065/e3bb43b3-a095-41f6-b4ac-631aed7d6f33)

**Comment by Greenheart** [comment]
Tack själv! Det här blev en klar förbättring eftersom kartan för utsläppen bör likna den för koldioxidbudgetar. Jag är förvånad att detta har varit kvar så länge, med tanke på att det var en relativt enkel ändring. Men men, nu är det gjort iaf :)
