### ISSUE TITLE
The rows of the list view are not clickable in Safari 15.3 

### ISSUE THREAD

**Issue by elvbom** [Klimatbyran/klimatkollen#202]
Listvyn på startsidan: raderna med kommuner går inte att klicka på/navigera med i Safari 15.3. Har provat att lägga till tabIndex och byta onClick till onMouseOver, men utan att det hjälpt.

**Comment by LudwikJaniuk** [comment]
I don't have safari but it's working in Chrome. Can it still be reprouced?

**Comment by elvbom** [comment]
I can't reproduce this issue on Safari 17.2. I'm closing the issue for now, let's see if anyone else reports similar problems on Safari.
