### ISSUE TITLE
Fix broken test for FooterNewsletterSubscribe

### ISSUE THREAD

**Issue by elvbom** [Klimatbyran/klimatkollen#288]
FooterNewsletterSubscribe.test.tsx: Behöver kunna testa felhantering om NEXT_PUBLIC_MAILCHIMP_URL inte är satt, men testet fungerar inte i dagsläget.

**Comment by LudwikJaniuk** [comment]
Fixing a broken test is a good first issue because the goal is clearly set.

**Comment by Greenheart** [comment]
Closing since we removed these tests as part of #452. The main reason was that the Footer tests only tested UI copy rather than functionality.
