### ISSUE TITLE
Add sitemap and robots.txt

### ISSUE THREAD

**Issue by elvbom** [Klimatbyran/klimatkollen#347]

**Comment by LudwikJaniuk** [comment]
Context - klimatkollen.se currently has data on all the swedish municipalities, for emissions, bike lanes, and the other data points. So a google search for e.g. "koldioxidutsläpp alingsås" should list our page, but currently doesn't seem to on google. It's possible that adding a sitemap and robots.txt would help - which should explicitly point our all the municipalities. Some resoruces that could help:

https://docs.developers.optimizely.com/configured-commerce/v1.5.45-b2b-sdk/docs/improving-search-with-the-robotstxt-and-the-sitemap
https://developers.google.com/search/docs/crawling-indexing/robots/create-robots-txt

**Comment by Braggedtooth** [comment]
i can work on this. 

In next 14 it is possible to generate the sitemap dynamically
