### ISSUE TITLE
Add Discord logo + link in footer

### ISSUE THREAD

**Issue by elvbom** [Klimatbyran/klimatkollen#350]
Add Discord logo and link to our server https://discord.gg/FPX9yqYAmk in our footer, new to other social links

**Comment by MohitKambli** [comment]
Hello,
Hope you're doing well.
I would like to work on this issue.
However, when I tried setting up the project on my system, (referred this [part](https://github.com/Klimatbyran/klimatkollen?tab=readme-ov-file#get-started)) I got the following issue while running the `npm run dev` command.

![image](https://github.com/Klimatbyran/klimatkollen/assets/31406633/9ba43b9b-5281-433a-882a-1d1a220bceb4)

If at all there's any incorrect step that I am implementing or if I am missing some step, then kindly let me know.
Sincere apologies for the trouble being caused.

Thanks and Regards,
Mohit Kambli

**Comment by MohitKambli** [comment]
Hello @elvbom!
Hope you're doing well.
Thank you so much for your assistance.
Yes, I do have a Windows system.
I made the changes in the package.json file as you had mentioned in the previous comment.
Post that, I simple executed the following two commands, after which the server was up and running successfully:
```
npm i --save-dev cross-env
npm run dev
```
Now, according to the requirement, I have added the discord symbol in the footer section.
This is how it looks:
1)
![image](https://github.com/Klimatbyran/klimatkollen/assets/31406633/9fcf56cb-52d6-45df-9ad4-475b74087d41)

2)
![image](https://github.com/Klimatbyran/klimatkollen/assets/31406633/751fad9d-4fbb-457f-af12-a42a45f2189e)

Do you think this looks fine?
If at all there are any changes to be made then do let me know.
Sincere apologies if you find any mistakes from my end.

Thanks and Regards,
Mohit Kambli
