### ISSUE TITLE
Adapt municipality screen title to mobile

### ISSUE THREAD

**Issue by elvbom** [Klimatbyran/klimatkollen#363]
Municipality name title is huge on mobile rn, would be better to make it smaller. Maybe also align with left arrow + municipal coat of arms to save space?

<img width="438" alt="Screenshot 2024-02-21 at 11 49 37" src="https://github.com/Klimatbyran/klimatkollen/assets/7899748/105b5cbd-252c-4887-81e4-db1cbc5cf6cb">

**Comment by simonsteiger** [comment]
On it!

**Comment by LudwikJaniuk** [comment]
Status check - Is this resolved after the two PRs? (and thanks for you work @simonsteiger ! )
