### ISSUE TITLE
Change color thresholds for consumption emissions

### ISSUE THREAD

**Issue by elvbom** [Klimatbyran/klimatkollen#365]
Judging from current map, you can think that the consumption emissions are going quite well in terms of the map colors - it's mostly yellow. The truth is that already 5.5 tons of CO2/year/person (municipality in top of list) are really bad numbers, so this map should be considerably redder.

Map here: https://www.klimatkollen.se/konsumtionen/karta

**Comment by LudwikJaniuk** [comment]
Title - I suggest
"Change color thresholds for consumption emissions"

**Comment by LudwikJaniuk** [comment]
This is marked "good first issue" but the expectation is not that a first time contributor should know exactly what colors to assign. Instead, feel free to create a draft re-coloring and submit a PR along with a screenshot.
