### ISSUE TITLE
(vision) Visualize consumption-based emissions

### ISSUE THREAD

**Issue by LudwikJaniuk** [Klimatbyran/klimatkollen#369]
It would be great if we could visualize emissions caused by Swedish people's consumption, for example e-trade. Right now it's not at all clear how to do that - is there data? Where is it?

**Comment by LudwikJaniuk** [comment]
I understood it that the current ones don't include e-trade for example. Was that correct?

**Comment by elvbom** [comment]
Not quite sure about e-commerce, I emailed them and asked.

**Comment by LudwikJaniuk** [comment]
My understanding is still that the emissions data we have, from naturvårdsverket, doesn't include consumption-based emissions from e.g. e-trade. It is also my understanding that this data is largely unavailable in general. I'm going to close this issue to keep the issue set clean - it's not actionable by klimatkollen in the foreseeable future.

**Comment by elvbom** [comment]
For future reference, here is the response from SEI (that runs Konsumtionskompassen, our data provider):

Den information vi har från SCB om huruvida e-handel ingår i de konsumtionsbaserade data som tas fram för Sverige (och som vi utgår från) är att den e-handel hushållen gör i form av direktimport inte ingår (t.ex. inköp från WISH och liknande siter). Däremot ingår prylar du köper över nätet från svenska företag som Apoteket, HM osv.
