### ISSUE TITLE
Clarify map legends for scalar datasets

### ISSUE THREAD

**Issue by elvbom** [Klimatbyran/klimatkollen#378]
<img width="889" alt="Screenshot 2024-03-05 at 13 00 06" src="https://github.com/Klimatbyran/klimatkollen/assets/7899748/fd55cb22-4868-496c-a1de-da5cf9964876">

Could map legends be changed from `1 m -` to `Mindre än 1 meter`, and `5 m +` to `Mer än 5 m`? Has to be tested on mobile, but could be easier to understand. Has to be done for all (non-binary) datasets in utils/datasetDescriptions.tsx

**Comment by Greenheart** [comment]
To save space, and remove the need for translating these labels, maybe we could replace `1 m -` with `< 1m` and `5 m +` with `> 5 m`?

This would work on mobile without further adjustments, and remove the risk of some languages having much longer labels.

**Comment by elvbom** [comment]
> To save space, and remove the need for translating these labels, maybe we could replace `1 m -` with `< 1m` and `5 m +` with `> 5 m`?
> 
> This would work on mobile without further adjustments, and remove the risk of some languages having much longer labels.

I agree that the solution suggested above takes up too much space on mobile devices, but wonder if < and > might be harder for some people to understand. Closing this issue for now, let's see if it reappears during user testing.
