### ISSUE TITLE
Should the map's label boundaries be changed to better reflect what constitutes good development?

### ISSUE THREAD

**Issue by elvbom** [Klimatbyran/klimatkollen#385]
It's easy to believe that it's going OK with emissions if one looks at the homepage, when even a 10-15% reduction is actually not sufficient in most cases. Should the map's boundaries be changed so that users are better guided?

There is already a card for consumption emissions specifically, see #365 

<img width="860" alt="Screenshot 2024-03-07 at 08 18 50" src="https://github.com/Klimatbyran/klimatkollen/assets/7899748/a8cec585-84cb-4553-8bd1-c0211ee23a0d">

**Comment by LudwikJaniuk** [comment]
This issue needs discussion. It desribes both 1) a decision to be made, and 2) the actual implementation. A good start would be a screenshot with alternative color tresholds, to have a comparison draft to discuss (in discord)
