### ISSUE TITLE
Add municipality tooltips to map in mobile view

### ISSUE THREAD

**Issue by datalowe** [Klimatbyran/klimatkollen#396]
When viewing klimatkollen.se on a desktop/wide screen, upon hovering over a municipality its name and associated value is displayed. When viewing the site on a mobile device/narrow screen however, there is no corresponding tooltip - tapping a municipality brings you directly to its detailed view. This is unintuitive to most users and sometimes annoying, as you 1) might want to browse different municipalities, that you might not know the name of beforehand, and get an overview 2) are prone to accidentally going to a municipality's page when you attempt to just scroll on the main page.

Change the behavior on mobile view to display tooltips, which contain the same information as the desktop view's tooltips, and which have a link (either all of the popup, or as a text hyperlink in the popup) to the municipality's detailed view.

**Comment by LudwikJaniuk** [comment]
Agreed this would improve experience on mobile.

**Comment by datalowe** [comment]
The tooltip on desktop is generated by use of a callback that the `DeckGL` property `getToolTip` is set to right now, in 'components/Map/Map.tsx'. I thought at first that the way forward on mobile would be to somehow trigger the `getToolTip` event 'explicitly', by some kind of function call. However, I've been unable to find any documentation that would indicate that this is possible.

I looked around at "official" Deck.gl examples and found one project that appears to do essentially what we want here:

* https://deck.gl/examples/icon-layer
* https://github.com/visgl/deck.gl/tree/8.9-release/examples/website/wms

In their 'app.jsx', they use an element that's a neighbor of the `DeckGL` component to generate the tooltip, foregoing the use of `getToolTip` entirely and instead relying on a `selection` state variable:

```js
      <DeckGL layers={[layer]} initialViewState={initialViewState} controller={CONTROLLER} />
      {selection && (
        <div
          className="selected-feature-info"
          style={{left: selection.x, top: selection.y}}
          onPointerLeave={() => setSelection(null)}
        >
          {selection.featureInfo}
        </div>
      )}
```

In order to make tooltips work on mobile then, we might need to similarly move the tooltip JSX to a separate component. I'll try to experiment with it.

**Comment by LudwikJaniuk** [comment]
Great job @datalowe and with the nice final touch by @Greenheart this is now resolved.
