### ISSUE TITLE
Add sorting icon to column headers in Listvy

### ISSUE THREAD

**Issue by lalarus** [Klimatbyran/klimatkollen#405]
Currently, clicking on the table headings allows users to toggle between the data being shown in ascending/descending order.
This feature is very hidden (no curser pointer either).
I suggest to add a sorting icon: 

When a column is sortable, the sort icon will appear to the right of the column header in a white color. Clicking the icon triggers the arrow to point upwards/downwards and the content to be sorted in ascending/descending order.

**Comment by lalarus** [comment]
<img width="822" alt="Screenshot 2024-03-07 at 19 58 40" src="https://github.com/Klimatbyran/klimatkollen/assets/126619240/17350607-25c8-43cc-bb2c-94923cfa3f72">
<img width="105" alt="Screenshot 2024-03-07 at 20 06 55" src="https://github.com/Klimatbyran/klimatkollen/assets/126619240/c57b4286-97d2-4ce5-afaf-d08d14ea9bd1">

**Comment by Greenheart** [comment]
I think this is a great idea!

After working on fixing #474, it's obvious that this could make the sorting much clearer.

If anyone is interested in working on this, feel free to submit a PR! :slightly_smiling_face:

**Comment by Greenheart** [comment]
I'm working on this as part of #430. This will be enabled also when sorting data about municipalities.

**Comment by Greenheart** [comment]
This is now fixed as part of #543 

Thanks @lalarus for your clear suggestions for how this could work! The discussion in this issue and your PR review in #430 were both really helpful! :star2:
