### ISSUE TITLE
Update README to better describe process of creating a PR

### ISSUE THREAD

**Issue by elvbom** [Klimatbyran/klimatkollen#421]
Currently, there is no detailed description of how to make a PR to the repo. Specifically, it should be specified that one should run npm run build and npx eslint . --ext .js,.jsx,.ts,.tsx before making their PR, but perhaps there are other steps that should be described

**Comment by LudwikJaniuk** [comment]
Agreed, contribution guidelines such as a checklist before pushing, and perhaps other things, are needed. I'll prioritize adding this.

**Comment by Greenheart** [comment]
Completed in #489 - thanks @LudwikJaniuk! :tada:
