### ISSUE TITLE
Make so the map can't be moved out of view

### ISSUE THREAD

**Issue by LudwikJaniuk** [Klimatbyran/klimatkollen#462]
Right now it's too easy to accidentally swipe the map out-of-view, and then it's hard to find it again. Probably there is a way to limit the dragging of the map so this doesn't happen.
![image](https://github.com/Klimatbyran/klimatkollen/assets/6298393/4845bd73-8923-42d7-8751-7fbacbd8e063)

**Comment by datalowe** [comment]
I'm working on this, PR going up soon...
