### ISSUE TITLE
Consider removing the unneeded Borna font assets from the `public` directory

### ISSUE THREAD

**Issue by Greenheart** [Klimatbyran/klimatkollen#463]
For example, the demo pages are published to the live webpage. Maybe move this to another directory, and only preserve the actual font files we need in the public directory, since this would make our deployments smaller and more focused.

https://www.klimatkollen.se/fonts/Borna/webfontkit/borna-bold-demo.html

**Comment by LudwikJaniuk** [comment]
Just to clarify - this doesn't affect load time for users, right?

**Comment by Greenheart** [comment]
No, it's mainly cleaning up the repository size, which will affect git operations (including build times at Vercel).
