### ISSUE TITLE
Update the link to UU's carbon budget paper in the municipality's fact sheet

### ISSUE THREAD

**Issue by elvbom** [Klimatbyran/klimatkollen#468]
In the municipality's fact sheet, under "Koldioxidbudget", update the link to UU's carbon budget paper from 2022 years version to 2024.

Link atm: https://www.klimatkollen.se/Paris_compliant_Swedish_CO2_budgets-March_2022-Stoddard&Anderson.pdf
Should be replaced with: https://www.cemus.uu.se/wp-content/uploads/2023/12/Paris-compliant-carbon-budgets-for-Swedens-counties-.pdf

<img width="854" alt="Screenshot 2024-04-18 at 11 40 05" src="https://github.com/Klimatbyran/klimatkollen/assets/7899748/f90e6144-fffd-467f-86df-816dd405e219">

**Comment by Sparky338** [comment]
I can take care of this in the next 24 hours. I'm about to step away for the evening, but would like to be assigned to it. I'll also find other instances of the current link and update it as needed, as my brief look found at least 3 locations that the "March 2022" link or version is used.

**Comment by Sparky338** [comment]
This issue can be closed with the merge of PR #477.

**Comment by Greenheart** [comment]
Thank you @Sparky338! :smile:
