### ISSUE TITLE
Remove arrows from ToggleSections on mobile screens

### ISSUE THREAD

**Issue by elvbom** [Klimatbyran/klimatkollen#488]
![IMG_2960](https://github.com/Klimatbyran/klimatkollen/assets/7899748/f7217853-e4e2-446e-8e89-aae16ef70118)

**Comment by Greenheart** [comment]
One way to solve this could be to use the accordion component from https://ui.shadcn.com/docs/components/accordion. This would also solve some a11y issues.

The best timing for this issue would probably be when we implement the new design.

**Comment by Greenheart** [comment]
Solved by #494
