### ISSUE TITLE
Make the redirection from the 404 page to the home page automatic

### ISSUE THREAD

**Issue by elvbom** [Klimatbyran/klimatkollen#508]
Instead of prompting the user to push a button to be redirected to the home page from broken links, display a message stating that the link is broken and automatically redirect the user

**Comment by Greenheart** [comment]
This could be a toast component, either with a timed message showing for 10-15 sec (or until closed).

**Comment by inteoscar** [comment]
I'll start with this one

**Comment by SimonAM** [comment]
@inteoscar . Seems like i forgot to tell you i started on this as well. We can compare solutions if you want to (im sitting next to the windows in a red checkered shirt)

**Comment by inteoscar** [comment]
@SimonAM Ok! No worries, didn’t get that far anyway, you can take it. I had to go home :)
