### ISSUE TITLE
Remove extra arrows from expandable elements on the municipality page

### ISSUE THREAD

**Issue by elvbom** [Klimatbyran/klimatkollen#533]
Should not be arrows on left side of text.

![IMG_2976](https://github.com/Klimatbyran/klimatkollen/assets/7899748/34847eaf-7ffd-433d-a8ad-059ea74c1613)

**Comment by Greenheart** [comment]
Here's an example of how this could be fixed.

https://github.com/Klimatbyran/klimatkollen/pull/494
