### ISSUE TITLE
Improve table scrolling UX for `ComparisonTable`

### ISSUE THREAD

**Issue by Greenheart** [Klimatbyran/klimatkollen#551]
- Maybe use one scroll area (the whole page), (instead of an inner scroll area within the table) and make table header sticky compared to the website container
- Maybe use a sticky/fixed table footer so that information is always available.

- Maybe let the table be collapsed by default, and then open the full table with a toggle button. This would allow scrolling to sections further down, and get an overview.

This is partly inspired by feedback by Larry in https://github.com/Klimatbyran/klimatkollen/pull/430#pullrequestreview-2046218204

**Comment by lalarus** [comment]
I'm not sure if I understand what you mean with no. 3. 

Is it related to what I wrote here?
_Collapse details/accordion when clicking on another company row. Right now, an accordion element remains open when another accordion is opened._
