### ISSUE TITLE
Upprepade timeouts

### ISSUE THREAD

**Issue by osirisguitar** [Klimatbyran/klimatkollen#56]
Vet inte om det har specifik med Nykvarn att göra, men denna verkar inte funka: https://klimatkollen.se/kommun/nykvarn/historiska-utslapp

---

This Serverless Function has timed out.

Your connection is working correctly.

Vercel is working correctly.

504: GATEWAY_TIMEOUT
Code: FUNCTION_INVOCATION_TIMEOUT
ID: arn1::rdk2r-1647244976674-3ca7c5d203f3

If you are a visitor, contact the website owner or try again later.
If you are the owner, [learn how to fix the error](https://vercel.com/docs/error/application/FUNCTION_INVOCATION_TIMEOUT) and [check the logs](https://klimatkollen.se/_logs).

**Comment by mittistormen** [comment]
Det var inte specifikt för Nykvarn utan API:et som låg nere. Kolla gärna igen nu

**Comment by mittistormen** [comment]
Löst, se ovan
