### ISSUE TITLE
Show `+`/`-` and `%` signs to make table data easier to understand

### ISSUE THREAD

**Issue by Greenheart** [Klimatbyran/klimatkollen#577]
This is currently only relevant for the municipalities.

![image](https://github.com/Klimatbyran/klimatkollen/assets/6125097/c5e0010e-edde-455f-b61b-0b23500ffbbd)

To change this, we could update the formatting in https://github.com/Klimatbyran/klimatkollen/blob/b435f30629de70b66848daacc2c5a6a023023c2d/utils/datasetDefinitions.tsx, as part of the `formattedDatapoint` of each relevant dataset.

One relevant dataset to start with is `utslappen`, which can be seen in the screenshot above.

However, there are likely others too. So part of this task should also be about adding formatting to other relevant datasets too.

**Comment by elvbom** [comment]
This is a valuble idea from a user, but it has been tested before and was found to be too cluttery and not adding the value we hoped for. It's not impossible that we might reintroduce it, but if so the decision would need to be based on feedback from multiple users.
