### ISSUE TITLE
Show map first in "kommunerna"

### ISSUE THREAD

**Issue by LudwikJaniuk** [Klimatbyran/klimatkollen#592]
Currently when toggling to "kommunerna" the default is showing the table. But the map is much nicer. I think we should still show it first in the "kommunerna" view.

**Comment by Greenheart** [comment]
Agreed, this would be a nice change.

This is a one line fix:

https://github.com/Klimatbyran/klimatkollen/blob/b10f4982afaa8ac9149b7aa6a01113ca05d6d616/pages/index.tsx#L76

Remove the `${selectedDataView}` with `karta` to fix this.

**Comment by Greenheart** [comment]
This was fixed by @lalarus - thank you! :smile: :sparkles:
