### ISSUE TITLE
Update doc/contributing.md and doc/getting-started.md to introduce the new technologies

### ISSUE THREAD

**Issue by Greenheart** [Klimatbyran/klimatkollen#607]
**Description**
Since we are going to use technologies that probably will be new to most contributors, we should give good instructions for how to get started. Luckily, both Astro and Svelte both have good interactive tutorials that are beginner friendly.

In addition to describing the 

**Motivation**
We need good documentation to make the Klimatkollen frontend as approachable as possible.

**Definition of Done**

- [ ] getting-started.md includes updated information about the new technologies we use. The following message (and the links in it) could be used as a starting point: https://discord.com/channels/1049333222309371965/1217777853169668178/1245391646397563020
- [ ] In getting-started.md, we have added 1-2 sentences stating that a basic understanding of HTML, CSS and JS is recommended, and link to https://freecodecamp.org which is a great place to learn these fundamentals. Maybe put this in the beginning of the document.
- [ ] README.md, getting-started.md and contributing.md all include updated commands (e.g. `npm run dev` and similar) that work with the new technologies.
- [ ] contributing.md has been updated to include a relative markdown link to `./getting-started.md` to make it clear how to set up your development environment.
- [ ] The relative link in the section https://github.com/Klimatbyran/klimatkollen/blob/staging/README.md#contributing has been fixed

**When should it be done?**
The earlier we can have this in place, the easier it will be for contributors to get involved in implementing the new design. However, I will need to prioritize development in the near future, and will come back to this later. If anyone is interested in working on this issue, that would be more than welcome though! :)

**Contact person**
@Greenheart 

In addition to the Definition of Done, the following always apply:
 - Tests, building, and linting passes
 - No new warnings are introduced
 - User experience is not reduced
 - Code is well formatted and readable
See doc/contributing.md.

**Comment by deverestHood** [comment]
Hej! Jag skulle vilja hjälpa till med dokumentationen. Tack!

**Comment by deverestHood** [comment]
> **Definition of Done**
> 
> * [ ]  README.md, getting-started.md and **contributing.md** all include updated commands (e.g. `npm run dev` and similar) that work with the new technologies.

@Greenheart   Hej! För uppgiften ovan finns kommandot `npm run dev` i README.md och getting-started.md. Kan du berätta mer mig hur du vill att kommandot ska ingå i contributing.md? Tack!
