### ISSUE TITLE
Color blindness improvement on map

### ISSUE THREAD

**Issue by simonsteiger** [Klimatbyran/klimatkollen#610]
**Description**
The map currently uses a color scale with shade transitions which may be difficult to interpret for users who only see greyscale.

**Motivation**
The website should be inclusive and user-friendly for everyone, including those affected by rare forms of color blindness.

**Definition of Done**
The new color scale should correctly reflect the numeric gradient. In greyscale, the 10-15% category looks darker than the 5-10% category.
Inspiration could be taken from the [viridis color maps](https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html).

**When should it be done?**
Not urgent.

**Contact person**
@lalarus says "probably @Greenheart". 😝 

**Example**
![image](https://github.com/Klimatbyran/klimatkollen/assets/106233551/3d2136cd-7c5a-4562-be04-7dc3af25875c)

**Comment by Greenheart** [comment]
Thank you so much Simon! Excellent bug report and suggestions :smile: :ok_hand: 

I'll see if there's an easy way to make the color scale work both with and without color.

**Comment by Greenheart** [comment]
It's likely not perfect, but I think this was a big improvement compared to before. Please let us know if you find more improvements we could make :)

![image](https://github.com/Klimatbyran/klimatkollen/assets/6125097/34b15762-5789-4441-be92-beff8cfcf876)

**Comment by simonsteiger** [comment]
This looks great, I think the new scale works brilliantly in greyscale!
