### ISSUE TITLE
Mobile browser interprets emissions as callable phone numbers

### ISSUE THREAD

**Issue by lalarus** [Klimatbyran/klimatkollen#673]
**Describe the bug**
When going to klimatkollen.se on mobile, the mobile browser interprets longer emission numbers as phone numbers, underlining them. Clicking on the number opens a pop-up, allowing the user to call the "phone number". 
However, when I start scrolling, the option disappears again (number is not underlined and not clickable anymore).

I experienced this bug with the latest version of Safari on iOS 17.5.1

**To Reproduce**
1. Go to klimatkollen.se on your phone.
2. See that the value of i *värdekedjan* for *ABB* gets underlined and is clickable.

**Expected behavior**
Longer numbers must not be interpreted as callable phone numbers. 

**Screenshots**
<img src="https://github.com/Klimatbyran/klimatkollen/assets/126619240/9de5696a-f98c-42a8-8b19-4c9873560336)" width="300">
<img src="https://github.com/Klimatbyran/klimatkollen/assets/126619240/916006c3-8069-4c44-a075-05f864b33bd5)" width="300">

**Comment by Greenheart** [comment]
Thanks! Will investigate

**Comment by Greenheart** [comment]
@lalarus Would you like to make this change and verify that it solves the problem? :)

**Comment by lalarus** [comment]
@Greenheart Thanks for the link! Yes, I'll try to fix this :)

**Comment by Greenheart** [comment]
Good idea adding `Fix for #673` to the PR description. It was almost correct. For future PRs that should close an issue, you need to use the `Fix #673` format to make GitHub automatically close the linked issue.

Here's the documentation showing all keywords and how to use them:
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue 

I usually only use `Fix #673` to keep it simple :)

**Comment by lalarus** [comment]
Ah, I see! Thanks so much for explaining this 🥲
