### ISSUE TITLE
Get data for company list from API instead of from a static file

### ISSUE THREAD

**Issue by Greenheart** [Klimatbyran/klimatkollen#685]
**Motivation**
This is needed to make the list of companies align with the actual companies that are available. We will also only have one place where we need to make changes (the company database) rather than updating the static file and re-building the website as well.

**Definition of Done**
This is done when we have...
- [ ] Removed the static file with companies from the frontend project
- [x] Are loading companies during runtime to show in the company list

**When should it be done?**
In the next few days, since we want to avoid discrepancies between the list view and the details view.

**Contact person**
@Greenheart

**Comment by irony** [comment]
Den här ska väl ligga på Beta nu? Inte på gamla sidan?

**Comment by elvbom** [comment]
Jag tänker att den ska vara på legacy-sidan iom att vi inte har motsvarande sida klar i beta (eller har jag missat ngt?)
