### ISSUE TITLE
Justera Christians bio

### ISSUE THREAD

**Issue by Klimatkollen** [Klimatbyran/klimatkollen#692]
Ändra i texten om Christian 

Engelska sidan, https://www.klimatkollen.se/in-english
ändra från "to the Swedish Government" till "Swedish Minister of Innovation"

Svenska sidan, https://www.klimatkollen.se/om-oss
ändra från "Sveriges innovationsminister" till "regeringen"?

**Comment by elvbom** [comment]
Fixed #691
